# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

spiral_scan_lines <- function(beam_divergence_angle, compensate_angle, FOU) {
    .Call('_spiralScan_spiral_scan_lines', PACKAGE = 'spiralScan', beam_divergence_angle, compensate_angle, FOU)
}

